# Site settings
title: Neural Olin
header-img: img/home-bg.jpg
description: "Olin Data Science 2016 Final Project exploration into neural networks"
baseurl: "/DataScience16FinalProject"
url: "http://neuralolin.github.io"
github_username:  neuralolin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, github-pages]
